### PR TITLE
Junit5 support

### PR DESCRIPTION
**Pull request by norrs**
Pull in junit5.x using the vintage engine to support the junit 4 engine
and associated tests.

Provide Extensions for Junit5 for which was available as Rules for
Junit4.

### CODE REVIEW

**Comment by norrs** [comment]
@jhannes I could move the `Extension`'s to the junit5 module instead of upgrading junit and including the vintage engine which is able to run junit4 tests? 

But would love to have a release with the extensions

**Comment by norrs** [comment]
This requires some more work, as all imports need to make sure they come from Junit5 and not Junit4.
ie Assert vs Assertions etc. 
I just fixed a version internally at work which passes (copied and ported class to Kotlin), I'll come back and fix this PR after Ive solved using test containers with junit5. 

Let me know if you want it into the junit5 module or not.

**Comment by jhannes** [comment]
This looks like a good addition and I've been looking to do this. Is there any negative interaction between junit 4 and junit 5?

I don't understand what you mean by "module". Did you have in mind a separate logevents-junit5 maven module? This would definately an easy pull request to accept, but I would prefer if the main module would work with both junit 4 and junit 5.

**Comment by norrs** [comment]
@jhannes For the best migration path, I would say the best would be to translate everything to jupiter APIs under junit5, then make a release with bundling junit vintage engine included. 

Then do a major version bump, change to junit5 engine and remove vintage. 

See the introduction here: https://junit.org/junit5/docs/current/user-guide/#overview-what-is-junit-5 

In our project we used jupiter api with vintage engine and junit:junit on classpath, until we refactored away from Rule's to extensions and then removed vintage and junit:junit and added jpiter engine for pure junit5 tests. 

Tho for test containers to work, we had to use the "hack" described here: https://github.com/testcontainers/testcontainers-java/issues/5404#issuecomment-1168669875 until they move to junit5. But we at least got rid of the junit4 dependency and everything is now junit5. 

When I was mentioning modules, I were thinking about `logevents-junit5-demo` you added .. but I belive maybe the approach I wrote above is good? Because if people need to stay on junit4, they still have the option to exclude the juniper engine implementation, and pull in the vintage engine explicit  together with junit5 juniper api. Vintage engine deals with briding junit4 impl with junit5 juniper api.

**Comment by norrs** [comment]
In other words, I can continue fixing rest of the imports etc to use the junit5 juniper engine and pull in junit5 vintage engine which is compatible with junit4, then rest of the clean up can happen in a major version bump if you follow semver-ish.

**Comment by jhannes** [comment]
Hope you had a good summer. I finally got around to reviewing the changes. I made some changes - for now I propose moving the junit5 support to a separate package. If you're happy with the changes, I can merge this now.

As for the major move to JUnit 5, I don't want logevents to be a library that forces its users to upgrade junit, even with the use of the vintage engine. But I'm happy with the idea of upgrading logevent's own tests to Jupiter. Does that seem like a good first step to you?

**Comment by jhannes** [comment]
@norrs You're correct about optional dependencies.

I've merged the pull request now.

Hope September will prove sunny. This summer was not the best time to be in Norway.

**Comment by jhannes** [comment]
@norrs  I'm struggling with releasing this pull request. After changing to `junit-vintage-engine` javadoc generation gives the error message `Exit code: 1 - javadoc: error - The code being documented uses packages in the unnamed module, but the packages defined in https://junit.org/junit5/docs/current/api/ are in named modules.`

This happens when I run `mvn javadoc:javadoc`, but Javadoc is also a requirement to release to central maven repository, so I can't release without it. I've been unable to find out remedy this.

**Comment by jhannes** [comment]
This pull request is released in version 0.4.1

**Pull request merged**
